run_tts:

run_freevc:
	python3.11 TTS/voice_conversion.py ../../data/input_T2S/test.wav ../../data/input_T2S/record_out_1.wav ../../data/output_T2S/outputFreeVC.wav

run_light_speed_ex:
	python3.11 test.py input_text.txt output.wav

run_light_speed:
	python3.11 light-speed/ckpts/test.py ../../data/input_T2S/trans_vie.txt ../../data/output_T2S/output.wav

run_xtts:
